name: Bundle Size Check

on:
  pull_request:
    branches:
      - main

jobs:
  build-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Analyze bundle size
        run: |
          echo "📦 Bundle Analysis"
          echo "================="

          if [ -d ".next" ]; then
            # Calculate total size
            TOTAL_SIZE=$(du -sh .next | cut -f1)
            echo "📊 Total build size: $TOTAL_SIZE"
            
            # List largest files
            echo ""
            echo "🔍 Largest files:"
            find .next -type f -name "*.js" -o -name "*.css" | xargs du -h | sort -rh | head -10
            
            echo ""
            echo "✅ Build completed successfully"
          else
            echo "❌ Build directory not found"
            exit 1
          fi
