name: Prettier

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prettier Action
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write "**/*.{ts,tsx,js,jsx,json,md}"
          only_changed: true
